# CI de nivel 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch
# gatilho de execução a partir de outro pipe = workflow_run

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed
# tarefas dentro do pipeline = jobs

jobs:
  e2e-tests:

    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # condicional - if
    # `${ expressao }´
    # == comparação

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # passos do script de build
    steps:
      # clone do projeto para dentro da máquina do Actions
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      #instalação das dependencias
      - name: Instalando dependencias
        run: yarn

      #instalação do Playwright (navegadores)
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report